version: 0.1.0-{build}

branches:
  except:
    - doc

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\checksums

install:
  - curl -L https://static.rust-lang.org/dist/rust-beta-x86_64-pc-windows-gnu.msi -oC:\rust-beta-x86_64-pc-windows-gnu.msi
  - start /w msiexec /qn /quiet /passive /a C:\rust-beta-x86_64-pc-windows-gnu.msi TARGETDIR="C:\Program Files"
  -
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Program Files\Rust\bin
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"

build: off
build_script:
  - git submodule update --init --recursive
  - cargo build --verbose

test: off
test_script:
  - cargo test --verbose

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
