version: 0.1.1-{build}

branches:
  except:
    - doc

skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\checksums

install:
  - curl -L https://static.rust-lang.org/dist/rust-1.10.0-x86_64-pc-windows-gnu.msi -oC:\rust-1.10.0-x86_64-pc-windows-gnu.msi
  - start /w msiexec /qn /quiet /passive /a C:\rust-1.10.0-x86_64-pc-windows-gnu.msi TARGETDIR="C:\Program Files"
  -
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Program Files\Rust\bin
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Sy"
  - bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"

build: off
build_script:
  - git submodule update --init --recursive
  - cargo build --verbose --release
  - cp target\release\checksums.exe checksums-v0.1.1.exe
  - strip --strip-all --remove-section=.comment --remove-section=.note checksums-v0.1.1.exe

test: off
test_script:
  - cargo test --verbose --release

artifacts:
  - path: checksums-v0.1.1.exe

deploy:
  provider: GitHub
  artifact: checksums-v0.1.1.exe
  auth_token:
    secure: zc/M0k0pSOFA3H9GhgTOFhYmOj6M88rfqwfjDhvhlzz/oa8P9JL+7XR4LmDHajJp
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    on_build_status_changed: true
